name: BADUA coverage Workflow

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set MAVEN_OPTS
      run: echo "MAVEN_OPTS=-Xms1G -Xmx2G" >> $GITHUB_ENV

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Maven build in ./common
      run: |
        cd common
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    - name: Maven build in ./core
      run: |
        cd core
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    # Costruisci il modulo core/spring
    - name: Maven build in ./core/spring
      run: |
        cd core/spring
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    - name: Switch to JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Badua Agent Jar
      run: |
        mvn install:install-file \
        -Dfile=./badua_file/ba-dua-agent-rt-0.6.0-all.jar \
        -DgroupId=br.usp.each.saeg \
        -DartifactId=ba-dua-agent-rt \
        -Dversion=0.6.0 \
        -Dclassifier=all \
        -Dpackaging=jar

    - name: Install Badua CLI Jar
      run: |
        mvn install:install-file \
        -Dfile=./badua_file/ba-dua-cli-0.6.0-all.jar \
        -DgroupId=br.usp.each.saeg \
        -DartifactId=ba-dua-cli \
        -Dversion=0.6.0 \
        -Dclassifier=all \
        -Dpackaging=jar

    - name: Run Badua coverage
      run: |
        mvn -B verify -Pbadua-coverage -Dcheckstyle.skip=true -Drat.skip=true

    - name: Upload Badua XML report
      uses: actions/upload-artifact@v3
      with:
        name: badua-report
        path: core/spring/target/badua.xml
