name: Build and Test with Badua

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MAVEN_OPTS: "-Xms2G -Xmx4G"

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    # Navigate to `core` and install ba-dua dependencies
    - name: Install Badua dependencies
      run: |
        cd core
        mvn install:install-file \
        -Dfile=./badua_file/ba-dua-agent-rt-0.6.0-all.jar \
        -DgroupId=br.usp.each.saeg \
        -DartifactId=ba-dua-agent-rt \
        -Dversion=0.6.0 \
        -Dclassifier=all \
        -Dpackaging=jar
        mvn install:install-file \
        -Dfile=./badua_file/ba-dua-cli-0.6.0-all.jar \
        -DgroupId=br.usp.each.saeg \
        -DartifactId=ba-dua-cli \
        -Dversion=0.6.0 \
        -Dclassifier=all \
        -Dpackaging=jar

    # Build project with Maven
    - name: Build project
      run: |
        mvn clean install -U -Dcheckstyle.skip=true

    # Navigate to `spring` and run tests with Badua coverage
    - name: Run tests with Badua
      run: |
        cd spring
        mvn -B verify -Pbadua-coverage -Dcheckstyle.skip=true

    # Upload the Badua report as an artifact
    - name: Upload Badua report
      uses: actions/upload-artifact@v3
      with:
        name: badua-report
        path: core/spring/target/badua.xml
