name: Jacoco coverage Workflow

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set MAVEN_OPTS
      run: echo "MAVEN_OPTS=-Xms1G -Xmx2G" >> $GITHUB_ENV

    #- name: Maven build in root directory
    #  run: mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true
    - name: Maven build in ./common
      run: |
        cd common
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true
      
    #- name: Maven build in ./core/persistence-api
    #  run: |
    #    mvn clean install -pl core/persistence-api -U -DskipTests -Dcheckstyle.skip=true -Drat.skip=true

    # Costruisci il modulo core
    - name: Maven build in ./core
      run: |
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    # Costruisci il modulo core/spring
    - name: Maven build in ./core/spring
      run: |
        mvn clean install -pl core/spring -U -DskipTests -Dcheckstyle.skip=true -Drat.skip=true

    - name: Run tests with Jacoco
      run: |
        mvn -B verify -Pjacoco -Dcheckstyle.skip=true -Drat.skip=true
