name: Jacoco coverage Workflow

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set MAVEN_OPTS
      run: echo "MAVEN_OPTS=-Xms1G -Xmx2G" >> $GITHUB_ENV

    #- name: Maven build in root directory
    #  run: |
    #    mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    #- name: Clean Maven Repository
    #  run: rm -rf ~/.m2/repository/org/apache/wicket

    - name: Maven build in ./archetype
      run: |
        cd ..
        cd archetype
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    - name: Maven build in ./client
      run: |
        cd ..
        cd client
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    - name: Maven build in ./common
      run: |
        cd ..
        cd common
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true
      

    - name: Maven build in ./core
      run: |
        cd core
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    - name: Maven build in ./core/spring
      run: |
        cd core
        cd spring
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    - name: Run tests with Jacoco
      run: |
        mvn -B verify -Pjacoco -Dcheckstyle.skip=true -Drat.skip=true
