name: Maven PIT Coverage Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  
    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Set MAVEN_OPTS
      run: echo "MAVEN_OPTS=-Xms1G -Xmx2G" >> $GITHUB_ENV

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Maven build in ./common
      run: |
        cd common
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    - name: Maven build in ./core
      run: |
        cd core
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    # Costruisci il modulo core/spring
    - name: Maven build in ./core/spring
      run: |
        cd core/spring
        mvn clean install -U -Dcheckstyle.skip=true -Drat.skip=true

    - name: Run PIT mutation coverage
      run: |
        cd core/spring
        mvn -B verify -Pmutation-coverage -Drat.skip=true
        
    - name: Upload PIT report
      uses: actions/upload-artifact@v3
      with:
        name: pit-reports
        path: core/spring/target/pit-reports/**
